### ISSUE TITLE
ValueError: No training descriptors given

### ISSUE THREAD

**Issue by paolovic** [AnyLoc/DINO#1]
Hi,
when using this code

```py
import torch
model = torch.hub.load("AnyLoc/DINO", "get_vlad_model", 
        backbone="DINOv2", device="cuda")
```

I am getting 

```bash

2024-06-23 17:04:02,985 - INFO - using SwiGLU layer as FFN
VLAD caching is disabled.
ValueError: No training descriptors given
```

Can you help me?

Thank you very much

**Comment by Nik-V9** [comment]
Hi, Thanks for trying out our code!

This indicates that it's not able to find the cluster centers in the torch cache. The code should try to download the cache by default. Not sure why that is not happening for you.

@TheProjectsGuy Tagging so that this is also visible to you.

**Comment by TheProjectsGuy** [comment]
Hey @paolovic

I tried the same commands on a fresh torch install and they're not giving any issues
![image](https://github.com/AnyLoc/DINO/assets/29420733/92c0866b-abc3-48b9-a32d-08ad09c18c89)

Are you behind a proxy? You should see the repository cloned to `~/.cache/torch/hub/AnyLoc_DINO_main` directory.

**Comment by paolovic** [comment]
Hi,
sorry, this has been resolved in the meantime.
Yes, I think, the cache was missing.
Thank you very much
Best regards
